config/routes.rb
Ninjahelper::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    resources :watches, :controller => "user_watched_courses", :only => [:create, :destroy, :index]
    #match "watched_courses" => "watch_courses#create", via: :post, as: :watched_courses
    #match "watched_courses/(:ccn)" => "watch_courses#delete", via: :delete, as: :watched_course
  end
  #match "check_course" => "watch_courses#check", via: :post, as: :check_course
end

app/controllers/user_watched_courses_controller.rb
class UserWatchedCoursesController < ApplicationController

  before_filter :authenticate_user!

  def render_json_errors(errors)
    render json: errors, status: 403
  end

  def create
    user = current_user
    course = Course.find_or_create_by(ccn: params[:ccn])
    if course.errors.any?
      render_json_errors course.errors
      return
    end
    if not course.ccn_valid?
      render_json_errors course: ["not found"]
      return
    end
    if not course.supported?
      render_json_errors course: ["is not supported currently"]
      return
    end
    if user.watched? course
      render_json_errors course: ["has already been watched"]
      return
    end
    if params[:monitor_type == '1'] and !course.is_waitlist_used
      render_json_errors course: ["The specified course does not have a waitlist."]
    end
    # if user.watched_courses.length >= 20 # TODO move this to configuration
    if user.can_watch_more_courses?
      render_json_errors user: ["can only watch up to 20 courses"]
      return
    end
    new_watch = Watch.new
    new_watch.user = user
    new_watch.course = course
    new_watch.wl= params[:monitor_type] == '1'
    new_watch.save!
    user.watches << new_watch
    course.watches << new_watch   #dont think this is necessary
    user.save!
    course.save!
    render json: course
  end

  def destroy
    user = current_user
    puts params
    watch = Watch.find(params[:id])
    if watch
      watch.delete
      respond_to do |format|
        format.json { render json: course }
        format.html { redirect_to :root }
      end
    else
      respond_to do |format|
        format.json { render_json_errors course: ["does not exist"] }
        format.html { redirect_to :root }
      end
    end
  end
end

app/helpers/user_watched_courses_helper.rb
module UserWatchedCoursesHelper
  
end

app/views/user_watched_courses/_manage.html.haml
- content_for :head do
  %script{type: "text/javascript"}
    if($$url === undefined) {
    var $$url = {};
    }
    $$url['watch_course'] = "#{user_watches_path(user)}"


.span8
  %h3 Monitored courses:

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th CCN
        %th Name
        %th Status
        %th &nbsp;
    %tbody
      - user.watches.sort_by(&:created_at).each do |watch| 
        - if watch
          - c = watch.course
          %tr
            %td= c.ccn
            %td= c.name
            %td= watch.status
            %td= link_to 'delete', user_watch_path(user, watch), method: :delete, class: 'btn'
        - else
          %tr No courses watched yet
  %p
    %a.btn.btn-primary{:'data-toggle' => 'modal', :'data-target' => '#new-course-modal'}
      %i.icon-white.icon-plus-sign
      New Course To Watch


.modal.hide.fade#new-course-modal
  .modal-header
    %button.close{:'data-dismiss' => 'modal'} x
    %h3 Add Course
  .modal-body
    = form_tag(user_watches_path(user), method: :post, id: 'user_watched_course_create')
    = label_tag(:ccn, 'CCN of the course:')
    = text_field_tag(:ccn)
    = label_tag(:monitor_type, 'Watch waitlist? ')
    = select_tag('monitor_type', options_for_select(['yes','no']))
    .br

    .alert.hide
    %a.btn{:'data-dismiss' => 'modal'} Close
    %input.btn.btn-primary{:type => 'submit', :value => 'Add Course'}